### ISSUE TITLE
Can't publish to master branch

### ISSUE THREAD

**Issue by ronaldbosma** [JamesRandall/Vsts-GitHub-Pages-Publish#7]
I want to use this task with my personal GitHub pages repository. I can only use master though while the task is always using gh-pages. So I want to be able to configure the branch to use.

See remark below from [https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages)

> If your site is a User or Organization Page that has a repository named username.github.io or  orgname.github.io, you cannot publish your site's source files from different locations. User and Organization Pages that have this type of repository name are only published from the master branch.

**Comment by JamesRandall** [comment]
Now pushed to the marketplace - thanks to @MarcBruins
